name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Uruchamiaj pipeline po pushu do gałęzi 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Klonuje repozytorium

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Użyj Node.js w wersji 20

      - name: Install dependencies
        run: |
          cd frontend/portfolio  # Przejdź do katalogu, gdzie znajduje się package.json
          npm install  # Instalacja zależności

      - name: Run tests
        run: |
          cd frontend/portfolio  # Przejdź do katalogu z testami
          npm test  # Uruchom testy

  deploy:
    needs: build  # Upewnij się, że etap budowy zakończył się pomyślnie
    runs-on: ubuntu-latest

    steps:
      - name: List files in frontend/portfolio
        run: ls -al frontend/portfolio  # Wyświetl zawartość katalogu, aby upewnić się, że pliki są dostępne

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}  # Adres IP serwera VPS
          username: ${{ secrets.VPS_USER }}  # Użytkownik na VPS
          key: ${{ secrets.VPS_PRIVATE_KEY }}  # Klucz prywatny SSH
          port: 22
          source: "frontend/portfolio"  # Przesyłaj folder portfolio
          target: "/home/ftpuser/var/www/portfolio/frontend"  # Ścieżka docelowa na VPS

      - name: Execute deployment script
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ftpuser/var/www/portfolio/frontend/portfolio  # Przejdź do katalogu aplikacji
            npm install --production  # Zainstaluj zależności produkcyjne
            pm2 restart app  # Uruchom aplikację na nowo (przy założeniu, że używasz PM2)
