name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Uruchamiaj pipeline po pushu do gałęzi 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Klonuje repozytorium

      - name: List root directory
        run: ls -al  # Wyświetl katalogi w głównym folderze roboczym

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Użyj Node.js w wersji 20

      - name: Install dependencies
        run: |
          cd frontend/portfolio  # Przejdź do katalogu, gdzie znajduje się package.json
          npm install  # Instalacja zależności

  deploy:
    needs: build  # Upewnij się, że etap budowy zakończył się pomyślniee
    runs-on: ubuntu-latest

    steps:
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS using rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        run: |
          # Konfiguracja ssh-agent i dodanie klucza prywatnego
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
          # Przesyłanie plików z użyciem rsync
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
            ./frontend/portfolio/ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/home/ftpuser/var/www/portfolio/frontend/portfolio/

      - name: Execute deployment script
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}  # Użyj klucza zamiast hasła
          port: 22
          script: |
            cd /home/ftpuser/var/www/portfolio/frontend/portfolio  # Przejdź do katalogu aplikacji
            npm install --production  # Zainstaluj zależności produkcyjne
            pm2 list 
            pm2 restart 1  # Uruchom aplikację na nowo (przy założeniu, że używasz PM2)
