name: Deploy to VPS

on:
  push:
    branches:
      - main  # Gałąź, którą chcesz monitorować

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Copy files to VPS
        run: |
          rsync -avz --exclude='.git' --exclude='node_modules' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/ftpuser/var/www/portfolio/frontend/portfolio

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Zmień na wersję Node.js, której używasz

      - name: Install dependencies and build
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd /home/ftpuser/var/www/portfolio/frontend/portfolio && npm install && npm run build'

      - name: Install PM2 globally (jeśli nie jest zainstalowany)
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'which pm2 || npm install -g pm2'

      - name: Restart application with PM2
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd /home/ftpuser/var/www/portfolio/frontend/portfolio && pm2 reload ecosystem.config.js --env production'

      - name: Optional: Save PM2 process list
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'pm2 save'
